
best_args = {'seq-cifar10': {
                    'sgd': {-1: {'lr': 0.1,
                                 'batch_size': 32,
                                 'n_epochs': 50}},
                    'ewc_on': {-1: {'lr': 0.03,
                                    'e_lambda': 10,
                                    'gamma': 1.0,
                                    'batch_size': 32,
                                    'n_epochs': 50}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50},
                           500: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 50}},
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.3,
                                  'batch_size': 32,
                                  'n_epochs': 50}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 50}},
                    'imex_reg': {200: {'lr': 0.03,
                                      'minibatch_size': 32,
                                      'batch_size': 32,
                                      'n_epochs': 50,
                                      'reg_weight':0.3,
                                      'ema_update_freq':0.4,
                                      'ema_alpha': 0.999,
                                      'ecr_weight':0.1,
                                      'crl_weight':0.1,
                                      'img_size':32},
                                500: {'lr': 0.03,
                                      'minibatch_size': 32,
                                      'batch_size': 32,
                                      'n_epochs': 1,
                                      'reg_weight':0.3,
                                      'ema_update_freq':0.4,
                                      'ema_alpha': 0.999,
                                      'ecr_weight':0.2,
                                      'crl_weight':0.1,
                                      'img_size':32}}
                    },
    'seq-cifar100': {
                     'sgd': {-1: {'lr': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 50}},
                     'ewc_on': {-1: {'lr': 0.03,
                                     'e_lambda': 10,
                                     'gamma': 1.0,
                                     'batch_size': 32,
                                     'n_epochs': 50}},
                     'er': {200: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50},
                            500: {'lr': 0.1,
                                  'minibatch_size': 32,
                                  'batch_size': 32,
                                  'n_epochs': 50}},
                     'der': {200: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.3,
                                   'batch_size': 32,
                                   'n_epochs': 50},
                             500: {'lr': 0.03,
                                   'minibatch_size': 32,
                                   'alpha': 0.3,
                                   'batch_size': 32,
                                   'n_epochs': 50}},
                     'derpp': {200: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.1,
                                     'beta': 0.5,
                                     'batch_size': 32,
                                     'n_epochs': 50},
                               500: {'lr': 0.03,
                                     'minibatch_size': 32,
                                     'alpha': 0.2,
                                     'beta': 0.5,
                                     'batch_size': 32,
                                     'n_epochs': 1}},
                     'imex_reg': {200: {'lr': 0.03,
                                       'minibatch_size': 32,
                                       'batch_size': 32,
                                       'n_epochs': 50,
                                      'reg_weight':0.15,
                                      'ema_update_freq':0.08,
                                      'ema_alpha': 0.999,
                                      'ecr_weight':0.3,
                                      'crl_weight':0.1,
                                      'img_size':32},
                                 500: {'lr': 0.03,
                                       'minibatch_size': 32,
                                       'batch_size': 32,
                                       'n_epochs': 50,
                                      'ema_alpha': 0.999,
                                    'reg_weight':0.15,
                                      'ema_update_freq':0.08,
                                      'ecr_weight':0.2,
                                      'crl_weight':0.1,
                                      'img_size':32}}
                     },
    'seq-tinyimg': {
                    'sgd': {-1: {'lr': 0.03,
                                 'batch_size': 32,
                                 'n_epochs': 100}},
                    'ewc_on': {-1: {'lr': 0.03,
                                    'e_lambda': 25,
                                    'gamma': 1.0,
                                    'batch_size': 32,
                                    'n_epochs': 100}},
                    'er': {200: {'lr': 0.1,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 100},
                           500: {'lr': 0.03,
                                 'minibatch_size': 32,
                                 'batch_size': 32,
                                 'n_epochs': 100}},
                    'der': {200: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'softmax_temp': 2.0,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 100},
                            500: {'lr': 0.03,
                                  'minibatch_size': 32,
                                  'alpha': 0.1,
                                  'batch_size': 32,
                                  'n_epochs': 100}},
                    'derpp': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.1,
                                    'beta': 1.0,
                                    'batch_size': 32,
                                    'n_epochs': 100},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'batch_size': 32,
                                    'n_epochs': 100}},
                    'imex_reg': {200: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 20,
                                      'ema_alpha': 0.999,
                                    'reg_weight':0.2,
                                      'ema_update_freq':0.1,
                                      'ecr_weight':0.1,
                                      'crl_weight':0.1,
                                      'img_size':64},
                              500: {'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 20,
                                    'ema_alpha': 0.999,

                                      'reg_weight':0.3,
                                      'ema_update_freq':0.15,
                                      'ecr_weight':0.1,
                                      'crl_weight':0.1,
                                      'img_size':64}}
                    },
        'gcil-cifar100': {
                        'sgd': {
                            'unif': {
                            -1: {
                                'lr': 0.1,
                                'batch_size': 32,
                                'n_epochs': 100
                                }
                            },
                            'longtail': {
                                -1: {
                                    'lr': 0.1,
                                    'batch_size': 32,
                                    'n_epochs': 100
                                }
                            },
                        },
                        'er': {
                            'unif': {
                                200: {
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                500: {
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                1000: {
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                            },
                            'longtail': {
                                200: {
                                    'alpha': 0.2,
                                    'beta': 0.6,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                500: {
                                    'alpha': 0.2,
                                    'beta': 0.8,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                1000: {
                                    'alpha': 0.3,
                                    'beta': 0.9,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                            },
                        },
                        'derpp': {
                            'unif': {
                                200: {
                                    'alpha': 0.2,
                                    'beta': 0.5,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                500: {
                                    'alpha': 0.2,
                                    'beta': 0.6,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                1000: {
                                    'alpha': 0.3,
                                    'beta': 0.6,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                            },
                            'longtail': {
                                200: {
                                    'alpha': 0.2,
                                    'beta': 0.6,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                500: {
                                    'alpha': 0.2,
                                    'beta': 0.8,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                1000: {
                                    'alpha': 0.3,
                                    'beta': 0.9,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                            },
                        },
                        'clser': {
                            'unif': {
                                200: {
                                    'reg_weight': 0.15,
                                    'stable_model_update_freq': 0.6,
                                    'stable_model_alpha': 0.999,
                                    'plastic_model_update_freq': 0.7,
                                    'plastic_model_alpha': 0.999,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 200,
                                },
                                500: {
                                    'reg_weight': 0.15,
                                    'stable_model_update_freq': 0.6,
                                    'stable_model_alpha': 0.999,
                                    'plastic_model_update_freq': 0.9,
                                    'plastic_model_alpha': 0.999,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                1000: {
                                    'reg_weight': 0.15,
                                    'stable_model_update_freq': 0.6,
                                    'stable_model_alpha': 0.999,
                                    'plastic_model_update_freq': 0.8,
                                    'plastic_model_alpha': 0.999,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                            },
                            'longtail': {
                                200: {
                                    'reg_weight': 0.1,
                                    'stable_model_update_freq': 0.6,
                                    'stable_model_alpha': 0.999,
                                    'plastic_model_update_freq': 0.7,
                                    'plastic_model_alpha': 0.999,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                500: {
                                    'reg_weight': 0.1,
                                    'stable_model_update_freq': 0.6,
                                    'stable_model_alpha': 0.999,
                                    'plastic_model_update_freq': 0.7,
                                    'plastic_model_alpha': 0.999,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                1000: {
                                    'reg_weight': 0.1,
                                    'stable_model_update_freq': 0.6,
                                    'stable_model_alpha': 0.999,
                                    'plastic_model_update_freq': 0.8,
                                    'plastic_model_alpha': 0.999,
                                    'lr': 0.1,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                            },
                        },
            'imex_reg': {
                            'unif': {
                                100: {
                                    'reg_weight': 0.15,
                                    'ema_update_freq': 0.1,
                                    'ema_alpha': 0.999,
                                    'ecr_weight': 0.2,
                                    'crl_weight': 0.2,
                                    'img_size': 32,
                                    'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                200: {
                                    'reg_weight': 0.15,
                                    'ema_update_freq': 0.1,
                                    'ema_alpha': 0.999,
                                    'ecr_weight': 0.2,
                                    'crl_weight': 0.2,
                                    'img_size': 32,
                                    'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                500: {
                                    'reg_weight': 0.15,
                                    'ema_update_freq': 0.1,
                                    'ema_alpha': 0.999,
                                    'ecr_weight': 0.2,
                                    'crl_weight': 0.2,
                                    'img_size': 32,
                                    'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                            },
                            'longtail': {
                                200: {
                                    'reg_weight': 0.15,
                                    'ema_update_freq': 0.1,
                                    'ema_alpha': 0.999,
                                    'ecr_weight': 0.2,
                                    'crl_weight': 0.2,
                                    'img_size': 32,
                                    'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                500: {
                                    'reg_weight': 0.15,
                                    'ema_update_freq': 0.1,
                                    'ema_alpha': 0.999,
                                    'ecr_weight': 0.2,
                                    'crl_weight': 0.2,
                                    'img_size': 32,
                                    'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                                1000: {
                                    'reg_weight': 0.15,
                                    'ema_update_freq': 0.1,
                                    'ema_alpha': 0.999,
                                    'ecr_weight': 0.2,
                                    'crl_weight': 0.2,
                                    'img_size': 32,
                                    'lr': 0.03,
                                    'minibatch_size': 32,
                                    'batch_size': 32,
                                    'n_epochs': 100,
                                },
                            },
                        },
    }
}
